######################################################################
# Automatically generated by qmake (2.01a) Sa. Mrz 27 18:31:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += . GeneratedFiles
MOC_DIR = GeneratedFiles
UI_DIR = GeneratedFiles
OBJECTS_DIR = obj

# Input
HEADERS += MainDlgHandler.h
FORMS += MainDlg.ui
SOURCES += main.cpp MainDlgHandler.cpp
